### ISSUE TITLE
Array List or Tuple of integer is not supported

### ISSUE THREAD

**Issue by pohlee** [davidaurelio/hashids-python#25]
Seems like hashids.encode did not accept Array or Tuple argument. while the site said it could convert array of numbers like [27, 986] into “3kTMd”.

it work if hashids.encode(1,2,3),
but if i pass in array like hashids.encode([1,2,3])
it will return 
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple' / 'list'

this is not an issue if using hashids.js

it could be simply fix by adding another IF to check the values is list or not in line 226

Thanks!

**Comment by pohlee** [comment]
my temporary solution is to add 

`        if values and (type(values[0]) == list or type(values[0]) == tuple):
            values = values[0]
`
into line 226 of encode funtion

**Comment by davidaurelio** [comment]
Hi @pohlee. I am very sorry for letting you wait for over two years.

> while the site said it could convert array of numbers like [27, 986] into “3kTMd”.

I am not sure whether that is mentioned anywhere for the python version.

However, you can simply unpack your tuple or list when calling like this:

```py
hashids.encode(*[1,2,3])
```
