### ISSUE TITLE
Encoding ids from separate entities and avoiding collisions

### ISSUE THREAD

**Issue by santiagobasulto** [davidaurelio/hashids-python#28]
Hello 👋 ! Great library @davidaurelio, thanks for putting it together :)

I have a question (a little bit conceptual). Let's say you have two entities/models (Cars and Customers, for example) and you want to generate hashids for them. What's the best way to decode a hashed id (for example `xd3rpH7vEp`) and realize what entity type it is? I have the following Idea:

```python
BASE_SECRET = "AshD(/084138(/%47iasjd"
hasher = Hashids(salt=BASE_SECRET, min_length=10)

# 1 for cars
# 2 for customers
hasher.encode(1, 115)  # 'xd3rpH7vEp'

hasher.decode('xd3rpH7vEp') # (1, 115) it's a car.
```

Is it correct? I don't know if it could be a collision with this scheme. Thanks very much!

**Comment by malefice** [comment]
The numbers you pass really have no meaning from the point of view of the library. What the numbers mean will depend on the application's business logic, so I do not think collisions will be an issue as long as your business logic implementation is correct.

**Comment by davidaurelio** [comment]
Hi @santiagobasulto. Apologies for not answering here for almost two years.

@malefice is right – there is no support for schemas etc. You will have to something as you suggested.

About collisions – I literally haven’t looked at the code for years. I am not aware of any edge cases or collisions.
