### ISSUE TITLE
_deprecated incorrectly warns that the wrapped function will be deprecated, rather than the assigned function

### ISSUE THREAD

**Issue by tstirrat15** [davidaurelio/hashids-python#29]
[These two lines](https://github.com/davidaurelio/hashids-python/blob/master/hashids.py#L214) should theoretically warn that `encrypt` and `decrypt` are deprecated functions. However, because they wrap the `encode` and `decode` functions, they warn that the `encode` and `decode` functions are deprecated, which is incorrect.

**Comment by davidaurelio** [comment]
Thanks for reporting this, and sorry for making you wait for over a year! I will go with the simple fix.
