### ISSUE TITLE
same hash for 199 and 111 with hashids-1.2.0

### ISSUE THREAD

**Issue by zhongyiio** [davidaurelio/hashids-python#34]
```
from hashids import Hashids

hashids = Hashids(salt='d3489ae5-5669-416b-b120-081f7cf39947', min_length=8)

hashids.encode(199) # 'O2aNK7vo'
hashids.encode(111) # 'O2aNK7vo'
```

**Comment by TimotheeJeannin** [comment]
Wow that's super scary ! The official docs says : 
> There are no collisions because the method is based on integer to hex conversion. As long as you don't change constructor arguments midway, the generated output will stay unique to your salt.

**Comment by carltongibson** [comment]
Look closer: 

```
>>> import hashids
>>> h = hashids.Hashids(salt='d3489ae5-5669-416b-b120-081f7cf39947', min_length=8)
>>> h.encode(199)
'O2aNk7vo'
>>> h.encode(111)
'O2aNK7vo'
>>> h.encode(199) == h.encode(111)
False
```

Why? `k` isn't the same as `K`.

**Comment by TimotheeJeannin** [comment]
Ha, thank you @carltongibson for pointing this. @zhongyiio I think this issue can be closed.
