### ISSUE TITLE
1.3.0 release breaks 1.2.0?

### ISSUE THREAD

**Issue by mwes** [davidaurelio/hashids-python#40]
I am trying to install hashids 1.2.0, which has worked for a long, long time. This currently fails under a python 3.7.7 venv. Is it possible your 1.3.0 release has affected the previous release of 1.2.0 somehow, e.g. with Flitch?

```
pip install hashids==1.2.0  
Collecting hashids==1.2.0
ERROR: Package 'hashids' requires a different Python: 3.7.7 not in '~=2.7,~=3.5'
```

https://github.com/davidaurelio/hashids-python/commit/7940cf6f3af0f3d4ebaa772a95be1bf9de9a9caf#diff-522adf759addbd3b193c74ca85243f7dR21

**Comment by ymtricks** [comment]
having the same problem

**Comment by csheppard** [comment]
Yes, just broke my build on Python 3.8.5 too

**Comment by davidaurelio** [comment]
Seems I messed this up, apologies! I won't get to it before Monday, european time. Can you fix your version to 1.2.0 until then, please?

If anyone would like to send a PR to fix this, that'd be greatly appreciated. I will merge it tomorrow morning.

**Comment by craigds** [comment]
We _do_ have the version pinned to 1.2.0, but we can't install 1.2.0 due to this bug for some reason

**Comment by davidaurelio** [comment]
I have yanked hashids 1.3.0 on pypi as a short term measure. I hope this will do the job. Will fix the version specifier tomorrow.

**Comment by davidaurelio** [comment]
no, not enough. The metadata is set persistently on pypi :-/

**Comment by craigds** [comment]
Thanks. Actually I think a new wheel has been pushed for 1.2.0 recently. 

I downloaded it and:

```
$ pip install hashids-1.2.0-py2.py3-none-any.whl
Processing ./hashids-1.2.0-py2.py3-none-any.whl
ERROR: Package 'hashids' requires a different Python: 3.7.3 not in '~=2.7,~=3.5'
```

The .tar.gz pacakge for 1.2.0 is fine, only the wheel is broken. So you can workaround with `pip -v install --no-binary :all: hashids==1.2.0`

@davidaurelio do you mind pulling the wheel for 1.2.0 also?

**Comment by davidaurelio** [comment]
@craigds done

- released v1.3.1
- deleted the wheel for v1.2.0 – you were right, v1.2.0 only ever had a sdist, no wheel. I set up pypi publishing via GH actions and managed to publish *that* today. 

I will take another good look at the GH action tomorrow. I hope everybody’s setup is working for now.

**Comment by craigds** [comment]
Thanks!

**Comment by davidaurelio** [comment]
I suppose we can close here.
