### ISSUE TITLE
Count of ids estimation

### ISSUE THREAD

**Issue by askaliuk** [davidaurelio/hashids-python#9]
Hello devs,
Thank you very much for awesome library.
Could you please help me to estimate count of ids based of characters limit.
For example,
_6 character long id with alphabet of X chars will provide Y of unique ids_
I've tried to calculate via simple `<alphabet length>^<length of id>` as it would work with `baseX` algorithm. But this is not the case.

Please help

**Comment by askaliuk** [comment]
@ducu sorry for late response. Unfortunately that was just a temporary script and didn't make notes about results. You may easily repeat them using your own script. The way to optimize it is to avoid checking each `+1` id, but increase a scale after each character change instead. E.g. between `4 chars` and `5 chars` you may easily do `+100` instead of `+1` and so on. It took less then 5 min for my script to provide good estimation.

**Comment by ducu** [comment]
Cool no problem, thanks for the tip!



—
Sent from Mailbox



On Wednesday 7 Jan 2015 at 21:17, Andrii Skaliuk <notifications@github.com>
